services:
  db:
    image: postgres:16
    container_name: cafe_pg
    environment:
      POSTGRES_USER: cafe
      POSTGRES_PASSWORD: cafe
      POSTGRES_DB: cafe
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: cafe_redis
    ports: [ "6379:6379" ]
volumes:
  pgdata:
