spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafe
    username: cafe
    password: cafe
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.show_sql: false
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
