spring:
  application:
    name: pos-cafe
  profiles:
    default: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
